- name: Upload pubic SSH key
  ec2_key:
    name: "{{ key_name }}"
    key_material: "{{lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub')}}"
    region: eu-central-1
    state: present

- name: Create default EC2 security group
  ec2_group:
    name: "{{ group }}"
    description: Default security group
    region: eu-central-1
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
    rules_egress:
          - proto: all
            from_port: 1
            to_port: 65535
            cidr_ip: 0.0.0.0/0

- name: Provision Fedora 25
  ec2:
    instance_type: "{{ instance_type | default('t2.medium') }}"
    region: eu-central-1
    image: ami-bac603d5 # Fedora 25
    group:  "{{ group }}"
    wait: yes
    instance_tags:
      name: "{{ instance_name | default('streamShift') }}"
    key_name: "{{ key_name }}"